[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'v3-periphery/=lib/v3-periphery/',
    'v3-core/=lib/v3-core/',
    '@uniswap=lib/',
    'oz-contracts/=lib/openzeppelin-contracts/contracts/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/'
]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config